window.GroupingList = ["Showcase", "Grids", "Navigation", "Layout", "Data Visualization", "Editors", "File Viewer", "Business Intelligence", "Notification", "Reporting"];
window.SamplesList = [
    {
        "Grids": ["Grid", "TreeGrid", "Spreadsheet"],
        "Navigation": ["Button", "Menu", "Ribbon", "Tab", "ListBox", "Rotator", "TreeView", "Accordion", "NavigationDrawer", "RadialMenu", "FileExplorer", "Toolbar"],
        "Layout": ["Splitter", "ListView", "Dialog", "ScrollBar", "TileView", "Tooltip"],
        "Data Visualization": ["Chart", "Schedule", "Kanban Board", "Diagram", "Gantt", "Map", "Barcode", "TreeMap", "HeatMap", "Sparkline", "SunburstChart","CircularGauge", "LinearGauge", "DigitalGauge", "BulletGraph", "RangeNavigator", "TagCloud"],
        "Editors": ["Autocomplete", "ComboBox", "DatePicker", "TimePicker", "DateTimePicker","DateRangePicker", "TextBoxes", "ColorPicker", "RadialSlider", "DropDownList", "Uploadbox", "Rating", "Slider", "RTE", "Signature"],
        "File Viewer": ["PDFViewer"],
        "Business Intelligence": ["PivotGrid (OLAP)", "PivotGrid (Relational)", "PivotChart (OLAP)", "PivotChart (Relational)", "PivotGauge (OLAP)", "PivotGauge (Relational)", "PivotTreeMap"],
        "Notification": ["ProgressBar", "WaitingPopup"],
        "Reporting": ["ReportViewer"],
    }
];
window.samplelists = [
    {
        "Grid": ["Grid"],
        "Button": ["Button"],
        "Menu": ["Default"],
        "Tab": ["Default"],
        "Dialog": ["Dialog"],
        "ListBox": ["ListBox"],
        "ListView": ["ListView"],
        "Autocomplete": ["Autocomplete"],
        "ComboBox": ["ComboBox"],
        "RadialMenu": ["RadialMenu"],
        "RadialSlider": ["RadialSlider"],
        "Splitter": ["Splitter"],
        "TileView": ["TileView"],
        "Rotator": ["Rotator"],
        "NavigationDrawer": ["NavigationDrawer"],
        "Accordion": ["Default"],
        "ColorPicker": ["ColorPicker"],
        "DatePicker": ["DatePicker"],
        "DateTimePicker": ["DateTimePicker"],
        "DateRangePicker":["DateRangePicker"],
        "DropDownList": ["Default"],
        "PDFViewer": ["Default"],
        "ProgressBar": ["Default"],
        "Rating": ["Default"],
        "ReportViewer": ["Default"],
        "RTE": ["Default"],
        "TagCloud": ["Default"],
        "Toolbar": ["Default"],
        "Tooltip": ["Default"],
        "Uploadbox": ["Default"],
        "WaitingPopup": ["Default"],
        "Kanban Board": ["Default"],
        "Ribbon": ["Default"],
        "Gantt": ["Gantt"],
        "TreeGrid": ["TreeGrid"],
        "Schedule": ["Schedule"],
        "ScrollBar": ["Scrollbar"],
        "Spreadsheet": ["Default"],
        "Slider": ["RangeSlider"],
        "TreeView": ["Default"],
        "TimePicker": ["TimePicker"],
        "TextBoxes": ["Default"],
        "FileExplorer": ["Default"],
        "PivotGrid (OLAP)": ["Default"],
        "PivotGrid (Relational)": ["Relational"],
        "PivotChart (OLAP)": ["Default"],
        "PivotChart (Relational)": ["Relational"],
        "PivotGauge (OLAP)": ["Default"],
        "PivotGauge (Relational)": ["Relational"],
        "PivotTreeMap": ["Default"],
        "Diagram": ["Diagram"],
        "HeatMap": ["HeatMap"],
        "Chart": ["Chart"],
        "BulletGraph": ["BulletGraph"],
        "CircularGauge": ["CircularGauge"],
        "LinearGauge": ["LinearGauge"],
        "DigitalGauge": ["DigitalGauge"],
        "RangeNavigator": ["RangeNavigator"],
        "Map": ["Map"],
        "Barcode": ["Barcode"],
        "TreeMap": ["TreeMap"],
        "Sparkline": ["Sparkline"],
        "Signature": ["Signature"],
		"SunburstChart":["SunburstChart"]
    }
];


